#!/bin/bash

# syntax: <file> $VANITY_KEY $TOTAL_ADDRESS_TO_GENERATE $DESTINATION_SITE_STORAGE_DIR $THREAD_COUNT

# syntax: <file> $VANITY_KEY -v -n $TOTAL_ADDRESS_TO_GENERATE -d $DESTINATION_SITE_STORAGE_DIR -t $THREAD_COUNT
SCRIPT_NAME=$(basename "$0")
VANITY_KEY="$1"
TOTAL_ADDRESS_TO_GENERATE="$2"
DESTINATION_SITE_STORAGE_DIR="$3"
THREAD_COUNT="$4"

# GENERATE VANITY ADDRESS
cd /opt/mkp224o/
./mkp224o "$VANITY_KEY" -v -n "$TOTAL_ADDRESS_TO_GENERATE" -d "$DESTINATION_SITE_STORAGE_DIR" -t "$THREAD_COUNT"

